spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  jpa:
    database:
      platform: org.hibernate.dialect.H2Dialect